import type { Scenario } from "@/lib/types";

export type LeverKey = keyof Scenario;

export type LeverGroup =
  | "Energy Supply"
  | "Transport"
  | "Buildings & Industry"
  | "Carbon Dioxide Removal"
  | "Other Sources of Greenhouse Gases"
  | "Land Use"
  | "Growth"
  | "India Specific";

export type LeverSpec = {
  key: LeverKey;
  title: string;
  unit: string;
  min: number;
  max: number;
  step: number;
  group: LeverGroup;
  help: string;
  lowLabel?: string;
  highLabel?: string;
  statusLabel?: string;
};

const status = "status quo";

export const leverSpecs: LeverSpec[] = [
  // Energy Supply
  {
    key: "Coal_action",
    title: "Coal",
    unit: "policy",
    min: -100,
    max: 100,
    step: 1,
    group: "Energy Supply",
    lowLabel: "discourage",
    highLabel: "encourage",
    statusLabel: status,
    help: "Discourage or encourage coal in the future energy mix. Negative values reduce coal share; positive values expand it.",
  },
  {
    key: "Oil_action",
    title: "Oil",
    unit: "policy",
    min: -100,
    max: 100,
    step: 1,
    group: "Energy Supply",
    lowLabel: "discourage",
    highLabel: "encourage",
    statusLabel: status,
    help: "Discourage or encourage oil. Transport electrification also lowers oil demand.",
  },
  {
    key: "Gas_action",
    title: "Natural Gas",
    unit: "policy",
    min: -100,
    max: 100,
    step: 1,
    group: "Energy Supply",
    lowLabel: "discourage",
    highLabel: "encourage",
    statusLabel: status,
    help: "Discourage or encourage natural gas in electricity and industry.",
  },
  {
    key: "Renewables2050_pct",
    title: "Renewables",
    unit: "% of total energy",
    min: 10,
    max: 95,
    step: 1,
    group: "Energy Supply",
    lowLabel: "low",
    highLabel: "very high",
    statusLabel: status,
    help: "Required renewable energy lever. Sets the 2050 target for renewable energy share (% of total energy proxy).",
  },
  {
    key: "Bioenergy_action",
    title: "Bioenergy",
    unit: "policy",
    min: -100,
    max: 100,
    step: 1,
    group: "Energy Supply",
    lowLabel: "discourage",
    highLabel: "encourage",
    statusLabel: status,
    help: "Changes bioenergy use. The model keeps bioenergy bounded to avoid unrealistic land pressure.",
  },
  {
    key: "Nuclear_action",
    title: "Nuclear",
    unit: "policy",
    min: -100,
    max: 100,
    step: 1,
    group: "Energy Supply",
    lowLabel: "discourage",
    highLabel: "encourage",
    statusLabel: status,
    help: "Changes future nuclear share of primary energy.",
  },
  {
    key: "NewZero_action",
    title: "New Zero‑Carbon",
    unit: "policy",
    min: -100,
    max: 100,
    step: 1,
    group: "Energy Supply",
    lowLabel: "none",
    highLabel: "breakthrough",
    statusLabel: status,
    help: "Represents future zero-carbon technologies such as advanced geothermal, long-duration storage, green hydrogen, or fusion-like breakthroughs.",
  },
  {
    key: "CarbonPrice_INR_tCO2",
    title: "Carbon Price",
    unit: "₹/tCO₂",
    min: 0,
    max: 15000,
    step: 100,
    group: "Energy Supply",
    lowLabel: "none",
    highLabel: "very high",
    statusLabel: status,
    help: "Applies a fossil-fuel penalty, reducing fossil shares and total energy demand. Expressed as ₹ per tCO₂.",
  },

  // Transport
  {
    key: "TransportEfficiency_action",
    title: "Energy Efficiency",
    unit: "policy",
    min: -100,
    max: 100,
    step: 1,
    group: "Transport",
    lowLabel: "lower",
    highLabel: "very high",
    statusLabel: status,
    help: "Improves vehicle efficiency and modal productivity. Positive values reduce transport energy demand.",
  },
  {
    key: "TransportElectrification_action",
    title: "Electrification",
    unit: "policy",
    min: -100,
    max: 100,
    step: 1,
    group: "Transport",
    lowLabel: "slow",
    highLabel: "very high",
    statusLabel: status,
    help: "Accelerates EVs, rail electrification, and electric two/three-wheelers. Reduces oil demand and raises electricity/clean energy demand.",
  },

  // Buildings & Industry
  {
    key: "BuildingsIndustryEfficiency_action",
    title: "Energy Efficiency",
    unit: "policy",
    min: -100,
    max: 100,
    step: 1,
    group: "Buildings & Industry",
    lowLabel: "lower",
    highLabel: "very high",
    statusLabel: status,
    help: "Improves buildings, appliances, industrial processes, and materials efficiency.",
  },
  {
    key: "BuildingsIndustryElectrification_action",
    title: "Electrification",
    unit: "policy",
    min: -100,
    max: 100,
    step: 1,
    group: "Buildings & Industry",
    lowLabel: "slow",
    highLabel: "very high",
    statusLabel: status,
    help: "Accelerates heat pumps, electric cooking, electric industrial heat, and other electrification pathways.",
  },

  // CDR
  {
    key: "NatureBasedRemoval_action",
    title: "Nature‑Based",
    unit: "policy",
    min: -100,
    max: 100,
    step: 1,
    group: "Carbon Dioxide Removal",
    lowLabel: "low",
    highLabel: "very high",
    statusLabel: status,
    help: "Adds biological CO₂ removal beyond the Forest Area slider. Includes restoration, agroforestry, and soil carbon proxies.",
  },
  {
    key: "TechRemoval_action",
    title: "Technological",
    unit: "policy",
    min: -100,
    max: 100,
    step: 1,
    group: "Carbon Dioxide Removal",
    lowLabel: "none",
    highLabel: "very high",
    statusLabel: status,
    help: "Adds engineered CO₂ removal (DAC, BECCS-like pathways) with a conservative India-scale cap.",
  },

  // Other GHG
  {
    key: "AgriculturalEmissions_action",
    title: "Agricultural Emissions",
    unit: "abatement",
    min: -100,
    max: 100,
    step: 1,
    group: "Other Sources of Greenhouse Gases",
    lowLabel: "higher",
    highLabel: "lower",
    statusLabel: status,
    help: "Reduces or increases methane and nitrous oxide proxies from agriculture. Positive = stronger abatement.",
  },
  {
    key: "WasteLeakage_action",
    title: "Waste and Leakage",
    unit: "abatement",
    min: -100,
    max: 100,
    step: 1,
    group: "Other Sources of Greenhouse Gases",
    lowLabel: "higher",
    highLabel: "lower",
    statusLabel: status,
    help: "Controls waste methane and fossil methane leakage proxies. Positive = stronger abatement.",
  },

  // Land use
  {
    key: "Deforestation_action",
    title: "Deforestation",
    unit: "policy",
    min: -100,
    max: 100,
    step: 1,
    group: "Land Use",
    lowLabel: "reforestation",
    highLabel: "high loss",
    statusLabel: status,
    help: "Positive values increase land-use emissions and reduce forest cover. Negative values support avoided deforestation/restoration.",
  },

  // Growth
  {
    key: "Pop2050_billion",
    title: "Population",
    unit: "B people in 2050",
    min: 1.1,
    max: 1.8,
    step: 0.01,
    group: "Growth",
    lowLabel: "lower",
    highLabel: "higher",
    statusLabel: status,
    help: "Population in 2050. After 2050, growth gradually flattens to a stable long-run path.",
  },
  {
    key: "GDPpc_CAGR_pct",
    title: "Economic Growth",
    unit: "%/yr GDPpc",
    min: 1.0,
    max: 7.5,
    step: 0.1,
    group: "Growth",
    lowLabel: "lower",
    highLabel: "higher",
    statusLabel: status,
    help: "Average GDP per capita growth. Raises demand unless offset by efficiency and decarbonization.",
  },

  // India-specific additions
  {
    key: "EI_improve_pct_per_year",
    title: "Energy Intensity Improvement",
    unit: "%/yr",
    min: 0,
    max: 6,
    step: 0.1,
    group: "India Specific",
    lowLabel: "slow",
    highLabel: "fast",
    statusLabel: status,
    help: "Required energy-efficiency proxy. This directly lowers energy intensity (MJ per $ PPP GDP).",
  },
  {
    key: "GridLoss2050_pct",
    title: "Grid T&D Losses",
    unit: "% in 2050",
    min: 3,
    max: 25,
    step: 0.2,
    group: "India Specific",
    lowLabel: "low losses",
    highLabel: "high losses",
    statusLabel: status,
    help: "Electricity transmission and distribution losses. Lower losses reduce required generation.",
  },
  {
    key: "CleanCooking2050_pct",
    title: "Clean Cooking Access",
    unit: "% in 2050",
    min: 40,
    max: 100,
    step: 1,
    group: "India Specific",
    lowLabel: "low",
    highLabel: "universal",
    statusLabel: status,
    help: "Health-first lever. Reduces PM2.5 exposure; can affect measured fossil CO₂ depending on LPG/electric mix.",
  },
  {
    key: "Urban2050_pct",
    title: "Urbanization",
    unit: "% in 2050",
    min: 25,
    max: 90,
    step: 1,
    group: "India Specific",
    lowLabel: "rural",
    highLabel: "urban",
    statusLabel: status,
    help: "Urban population share. Affects demand, PM exposure, and infrastructure efficiency proxies.",
  },
  {
    key: "Manuf2050_pct",
    title: "Manufacturing Share",
    unit: "% GDP in 2050",
    min: 5,
    max: 35,
    step: 0.5,
    group: "India Specific",
    lowLabel: "services-led",
    highLabel: "industry-led",
    statusLabel: status,
    help: "Higher manufacturing can raise energy intensity unless offset by efficiency and electrification.",
  },
  {
    key: "RD2050_pct_gdp",
    title: "Clean‑Tech R&D",
    unit: "% GDP in 2050",
    min: 0.1,
    max: 4,
    step: 0.05,
    group: "India Specific",
    lowLabel: "low",
    highLabel: "high",
    statusLabel: status,
    help: "Accelerates the renewable transition and efficiency improvements using calibrated data proxies.",
  },
  {
    key: "Forest2050_pct",
    title: "Forest Area",
    unit: "% land in 2050",
    min: 5,
    max: 60,
    step: 0.5,
    group: "India Specific",
    lowLabel: "lower",
    highLabel: "higher",
    statusLabel: status,
    help: "Adds a conservative forest carbon sink, constrained against land-use pressure.",
  },
  {
    key: "AirControls_strength",
    title: "Air Pollution Controls",
    unit: "strength",
    min: 0,
    max: 0.9,
    step: 0.05,
    group: "India Specific",
    lowLabel: "weak",
    highLabel: "strong",
    statusLabel: status,
    help: "Reduces PM2.5 exposure proxy without directly changing CO₂.",
  },
];

export const leverGroups: LeverGroup[] = [
  "Energy Supply",
  "Transport",
  "Buildings & Industry",
  "Carbon Dioxide Removal",
  "Other Sources of Greenhouse Gases",
  "Land Use",
  "Growth",
  "India Specific",
];
